### ISSUE TITLE
MVP: Build web service facilitating the Gossamer Flow (TM)

### ISSUE THREAD

**Issue by CaptainCalliope** [hellojwilde/gossamer#16]
The core functionality of Gossamer is shipping experimental front-end builds to users, enabling users to provide feedback in the form of analytics and github issues, and showing real-time data about those metrics

The web service will:
- Pull code from github and run relevant build processes
- Appropriately notify clients when new builds of the experiment that they're enrolled in are available
- Receive and store time-series analytics data about the performance of the extension to the browser
- Display the analytics data in real-time

The extension to browser.html will:
- Enable a user to start joining studies after logging in with GitHub
- Contain hooks for submitting analytics data
- Reload the browser after the user selects a particular experiment

![gossamerflowchart](https://cloud.githubusercontent.com/assets/50292/8393923/68cb0342-1cf1-11e5-87d6-1ce3c4a1c9a8.jpg)

**Comment by CaptainCalliope** [comment]
@hellojwilde: Is the issue text above still accurate? I copied it from a Trello card that's like two weeks old..

**Comment by hellojwilde** [comment]
I think they key thing that we've learned is that analytics are cool, but they're kinda a Demo 2 feature or something to quickly hack together with Keen.io.

Until we have a decent number of users it's kinda not that helpful. 

Replace "data" with "more concrete over the shoulder test results".
