### ISSUE TITLE
Write initial blog post about what happened in the last sprint and documenting goals for the future

### ISSUE THREAD

**Issue by hellojwilde** [hellojwilde/gossamer#5]

**Comment by CaptainCalliope** [comment]
So, you draft yours, I'll draft mine https://github.com/hellojwilde/gossamer/issues/7, we'll share, harmonize and then figure out when to hit publish on them! :D

**Comment by hellojwilde** [comment]
My draft of my post is here as I work on it: https://github.com/hellojwilde/hellojwilde.github.com/blob/master/_drafts/2015-06-27-gossamer-sprint-1.md
